server: 
  port: 8083
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:

    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.127.45:3306/relation?characterEncoding=utf8&useSSL=true
    username: appuser
    password: Hj965691203...

    tomcat:
      max-active: 10
      max-wait: 5000
      test-on-borrow: true
      
  http:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
      force-request: true
      force-response: true
    
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    generate-ddl: true
    
  security:
    user:
      name: wolf
      password: hj965691203
      
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8

    
    